///
//  Generated code. Do not modify.
//  source: pb/td/td_funcs.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type

import 'dart:async' as $async;

import 'package:protobuf/protobuf.dart' as $pb;

import 'dart:core' as $core;
import 'td_funcs.pb.dart' as $3;
import 'td_funcs.pbjson.dart';

export 'td_funcs.pb.dart';

abstract class tdServerServiceBase extends $pb.GeneratedService {
  $async.Future<$3.AcceptCallResponse> acceptCall($pb.ServerContext ctx, $3.AcceptCallRequest request);
  $async.Future<$3.AcceptTermsOfServiceResponse> acceptTermsOfService($pb.ServerContext ctx, $3.AcceptTermsOfServiceRequest request);
  $async.Future<$3.AddChatMemberResponse> addChatMember($pb.ServerContext ctx, $3.AddChatMemberRequest request);
  $async.Future<$3.AddChatMembersResponse> addChatMembers($pb.ServerContext ctx, $3.AddChatMembersRequest request);
  $async.Future<$3.AddFavoriteStickerResponse> addFavoriteSticker($pb.ServerContext ctx, $3.AddFavoriteStickerRequest request);
  $async.Future<$3.AddLocalMessageResponse> addLocalMessage($pb.ServerContext ctx, $3.AddLocalMessageRequest request);
  $async.Future<$3.AddNetworkStatisticsResponse> addNetworkStatistics($pb.ServerContext ctx, $3.AddNetworkStatisticsRequest request);
  $async.Future<$3.AddProxyResponse> addProxy($pb.ServerContext ctx, $3.AddProxyRequest request);
  $async.Future<$3.AddRecentStickerResponse> addRecentSticker($pb.ServerContext ctx, $3.AddRecentStickerRequest request);
  $async.Future<$3.AddRecentlyFoundChatResponse> addRecentlyFoundChat($pb.ServerContext ctx, $3.AddRecentlyFoundChatRequest request);
  $async.Future<$3.AddSavedAnimationResponse> addSavedAnimation($pb.ServerContext ctx, $3.AddSavedAnimationRequest request);
  $async.Future<$3.AddStickerToSetResponse> addStickerToSet($pb.ServerContext ctx, $3.AddStickerToSetRequest request);
  $async.Future<$3.AnswerCallbackQueryResponse> answerCallbackQuery($pb.ServerContext ctx, $3.AnswerCallbackQueryRequest request);
  $async.Future<$3.AnswerCustomQueryResponse> answerCustomQuery($pb.ServerContext ctx, $3.AnswerCustomQueryRequest request);
  $async.Future<$3.AnswerInlineQueryResponse> answerInlineQuery($pb.ServerContext ctx, $3.AnswerInlineQueryRequest request);
  $async.Future<$3.AnswerPreCheckoutQueryResponse> answerPreCheckoutQuery($pb.ServerContext ctx, $3.AnswerPreCheckoutQueryRequest request);
  $async.Future<$3.AnswerShippingQueryResponse> answerShippingQuery($pb.ServerContext ctx, $3.AnswerShippingQueryRequest request);
  $async.Future<$3.BlockUserResponse> blockUser($pb.ServerContext ctx, $3.BlockUserRequest request);
  $async.Future<$3.CancelDownloadFileResponse> cancelDownloadFile($pb.ServerContext ctx, $3.CancelDownloadFileRequest request);
  $async.Future<$3.CancelUploadFileResponse> cancelUploadFile($pb.ServerContext ctx, $3.CancelUploadFileRequest request);
  $async.Future<$3.ChangeChatReportSpamStateResponse> changeChatReportSpamState($pb.ServerContext ctx, $3.ChangeChatReportSpamStateRequest request);
  $async.Future<$3.ChangeImportedContactsResponse> changeImportedContacts($pb.ServerContext ctx, $3.ChangeImportedContactsRequest request);
  $async.Future<$3.ChangePhoneNumberResponse> changePhoneNumber($pb.ServerContext ctx, $3.ChangePhoneNumberRequest request);
  $async.Future<$3.ChangeStickerSetResponse> changeStickerSet($pb.ServerContext ctx, $3.ChangeStickerSetRequest request);
  $async.Future<$3.CheckAuthenticationBotTokenResponse> checkAuthenticationBotToken($pb.ServerContext ctx, $3.CheckAuthenticationBotTokenRequest request);
  $async.Future<$3.CheckAuthenticationCodeResponse> checkAuthenticationCode($pb.ServerContext ctx, $3.CheckAuthenticationCodeRequest request);
  $async.Future<$3.CheckAuthenticationPasswordResponse> checkAuthenticationPassword($pb.ServerContext ctx, $3.CheckAuthenticationPasswordRequest request);
  $async.Future<$3.CheckChangePhoneNumberCodeResponse> checkChangePhoneNumberCode($pb.ServerContext ctx, $3.CheckChangePhoneNumberCodeRequest request);
  $async.Future<$3.CheckChatInviteLinkResponse> checkChatInviteLink($pb.ServerContext ctx, $3.CheckChatInviteLinkRequest request);
  $async.Future<$3.CheckChatUsernameResponse> checkChatUsername($pb.ServerContext ctx, $3.CheckChatUsernameRequest request);
  $async.Future<$3.CheckDatabaseEncryptionKeyResponse> checkDatabaseEncryptionKey($pb.ServerContext ctx, $3.CheckDatabaseEncryptionKeyRequest request);
  $async.Future<$3.CheckEmailAddressVerificationCodeResponse> checkEmailAddressVerificationCode($pb.ServerContext ctx, $3.CheckEmailAddressVerificationCodeRequest request);
  $async.Future<$3.CheckPhoneNumberConfirmationCodeResponse> checkPhoneNumberConfirmationCode($pb.ServerContext ctx, $3.CheckPhoneNumberConfirmationCodeRequest request);
  $async.Future<$3.CheckPhoneNumberVerificationCodeResponse> checkPhoneNumberVerificationCode($pb.ServerContext ctx, $3.CheckPhoneNumberVerificationCodeRequest request);
  $async.Future<$3.CleanFileNameResponse> cleanFileName($pb.ServerContext ctx, $3.CleanFileNameRequest request);
  $async.Future<$3.ClearAllDraftMessagesResponse> clearAllDraftMessages($pb.ServerContext ctx, $3.ClearAllDraftMessagesRequest request);
  $async.Future<$3.ClearImportedContactsResponse> clearImportedContacts($pb.ServerContext ctx, $3.ClearImportedContactsRequest request);
  $async.Future<$3.ClearRecentStickersResponse> clearRecentStickers($pb.ServerContext ctx, $3.ClearRecentStickersRequest request);
  $async.Future<$3.ClearRecentlyFoundChatsResponse> clearRecentlyFoundChats($pb.ServerContext ctx, $3.ClearRecentlyFoundChatsRequest request);
  $async.Future<$3.CloseResponse> close($pb.ServerContext ctx, $3.CloseRequest request);
  $async.Future<$3.CloseChatResponse> closeChat($pb.ServerContext ctx, $3.CloseChatRequest request);
  $async.Future<$3.CloseSecretChatResponse> closeSecretChat($pb.ServerContext ctx, $3.CloseSecretChatRequest request);
  $async.Future<$3.CreateBasicGroupChatResponse> createBasicGroupChat($pb.ServerContext ctx, $3.CreateBasicGroupChatRequest request);
  $async.Future<$3.CreateCallResponse> createCall($pb.ServerContext ctx, $3.CreateCallRequest request);
  $async.Future<$3.CreateNewBasicGroupChatResponse> createNewBasicGroupChat($pb.ServerContext ctx, $3.CreateNewBasicGroupChatRequest request);
  $async.Future<$3.CreateNewSecretChatResponse> createNewSecretChat($pb.ServerContext ctx, $3.CreateNewSecretChatRequest request);
  $async.Future<$3.CreateNewStickerSetResponse> createNewStickerSet($pb.ServerContext ctx, $3.CreateNewStickerSetRequest request);
  $async.Future<$3.CreateNewSupergroupChatResponse> createNewSupergroupChat($pb.ServerContext ctx, $3.CreateNewSupergroupChatRequest request);
  $async.Future<$3.CreatePrivateChatResponse> createPrivateChat($pb.ServerContext ctx, $3.CreatePrivateChatRequest request);
  $async.Future<$3.CreateSecretChatResponse> createSecretChat($pb.ServerContext ctx, $3.CreateSecretChatRequest request);
  $async.Future<$3.CreateSupergroupChatResponse> createSupergroupChat($pb.ServerContext ctx, $3.CreateSupergroupChatRequest request);
  $async.Future<$3.CreateTemporaryPasswordResponse> createTemporaryPassword($pb.ServerContext ctx, $3.CreateTemporaryPasswordRequest request);
  $async.Future<$3.DeleteAccountResponse> deleteAccount($pb.ServerContext ctx, $3.DeleteAccountRequest request);
  $async.Future<$3.DeleteChatHistoryResponse> deleteChatHistory($pb.ServerContext ctx, $3.DeleteChatHistoryRequest request);
  $async.Future<$3.DeleteChatMessagesFromUserResponse> deleteChatMessagesFromUser($pb.ServerContext ctx, $3.DeleteChatMessagesFromUserRequest request);
  $async.Future<$3.DeleteChatReplyMarkupResponse> deleteChatReplyMarkup($pb.ServerContext ctx, $3.DeleteChatReplyMarkupRequest request);
  $async.Future<$3.DeleteFileResponse> deleteFile($pb.ServerContext ctx, $3.DeleteFileRequest request);
  $async.Future<$3.DeleteLanguagePackResponse> deleteLanguagePack($pb.ServerContext ctx, $3.DeleteLanguagePackRequest request);
  $async.Future<$3.DeleteMessagesResponse> deleteMessages($pb.ServerContext ctx, $3.DeleteMessagesRequest request);
  $async.Future<$3.DeletePassportElementResponse> deletePassportElement($pb.ServerContext ctx, $3.DeletePassportElementRequest request);
  $async.Future<$3.DeleteProfilePhotoResponse> deleteProfilePhoto($pb.ServerContext ctx, $3.DeleteProfilePhotoRequest request);
  $async.Future<$3.DeleteSavedCredentialsResponse> deleteSavedCredentials($pb.ServerContext ctx, $3.DeleteSavedCredentialsRequest request);
  $async.Future<$3.DeleteSavedOrderInfoResponse> deleteSavedOrderInfo($pb.ServerContext ctx, $3.DeleteSavedOrderInfoRequest request);
  $async.Future<$3.DeleteSupergroupResponse> deleteSupergroup($pb.ServerContext ctx, $3.DeleteSupergroupRequest request);
  $async.Future<$3.DestroyResponse> destroy($pb.ServerContext ctx, $3.DestroyRequest request);
  $async.Future<$3.DisableProxyResponse> disableProxy($pb.ServerContext ctx, $3.DisableProxyRequest request);
  $async.Future<$3.DiscardCallResponse> discardCall($pb.ServerContext ctx, $3.DiscardCallRequest request);
  $async.Future<$3.DisconnectAllWebsitesResponse> disconnectAllWebsites($pb.ServerContext ctx, $3.DisconnectAllWebsitesRequest request);
  $async.Future<$3.DisconnectWebsiteResponse> disconnectWebsite($pb.ServerContext ctx, $3.DisconnectWebsiteRequest request);
  $async.Future<$3.DownloadFileResponse> downloadFile($pb.ServerContext ctx, $3.DownloadFileRequest request);
  $async.Future<$3.EditCustomLanguagePackInfoResponse> editCustomLanguagePackInfo($pb.ServerContext ctx, $3.EditCustomLanguagePackInfoRequest request);
  $async.Future<$3.EditInlineMessageCaptionResponse> editInlineMessageCaption($pb.ServerContext ctx, $3.EditInlineMessageCaptionRequest request);
  $async.Future<$3.EditInlineMessageLiveLocationResponse> editInlineMessageLiveLocation($pb.ServerContext ctx, $3.EditInlineMessageLiveLocationRequest request);
  $async.Future<$3.EditInlineMessageMediaResponse> editInlineMessageMedia($pb.ServerContext ctx, $3.EditInlineMessageMediaRequest request);
  $async.Future<$3.EditInlineMessageReplyMarkupResponse> editInlineMessageReplyMarkup($pb.ServerContext ctx, $3.EditInlineMessageReplyMarkupRequest request);
  $async.Future<$3.EditInlineMessageTextResponse> editInlineMessageText($pb.ServerContext ctx, $3.EditInlineMessageTextRequest request);
  $async.Future<$3.EditMessageCaptionResponse> editMessageCaption($pb.ServerContext ctx, $3.EditMessageCaptionRequest request);
  $async.Future<$3.EditMessageLiveLocationResponse> editMessageLiveLocation($pb.ServerContext ctx, $3.EditMessageLiveLocationRequest request);
  $async.Future<$3.EditMessageMediaResponse> editMessageMedia($pb.ServerContext ctx, $3.EditMessageMediaRequest request);
  $async.Future<$3.EditMessageReplyMarkupResponse> editMessageReplyMarkup($pb.ServerContext ctx, $3.EditMessageReplyMarkupRequest request);
  $async.Future<$3.EditMessageTextResponse> editMessageText($pb.ServerContext ctx, $3.EditMessageTextRequest request);
  $async.Future<$3.EditProxyResponse> editProxy($pb.ServerContext ctx, $3.EditProxyRequest request);
  $async.Future<$3.EnableProxyResponse> enableProxy($pb.ServerContext ctx, $3.EnableProxyRequest request);
  $async.Future<$3.FinishFileGenerationResponse> finishFileGeneration($pb.ServerContext ctx, $3.FinishFileGenerationRequest request);
  $async.Future<$3.ForwardMessagesResponse> forwardMessages($pb.ServerContext ctx, $3.ForwardMessagesRequest request);
  $async.Future<$3.GenerateChatInviteLinkResponse> generateChatInviteLink($pb.ServerContext ctx, $3.GenerateChatInviteLinkRequest request);
  $async.Future<$3.GetAccountTTLResponse> getAccountTTL($pb.ServerContext ctx, $3.GetAccountTTLRequest request);
  $async.Future<$3.GetActiveLiveLocationMessagesResponse> getActiveLiveLocationMessages($pb.ServerContext ctx, $3.GetActiveLiveLocationMessagesRequest request);
  $async.Future<$3.GetActiveSessionsResponse> getActiveSessions($pb.ServerContext ctx, $3.GetActiveSessionsRequest request);
  $async.Future<$3.GetAllPassportElementsResponse> getAllPassportElements($pb.ServerContext ctx, $3.GetAllPassportElementsRequest request);
  $async.Future<$3.GetArchivedStickerSetsResponse> getArchivedStickerSets($pb.ServerContext ctx, $3.GetArchivedStickerSetsRequest request);
  $async.Future<$3.GetAttachedStickerSetsResponse> getAttachedStickerSets($pb.ServerContext ctx, $3.GetAttachedStickerSetsRequest request);
  $async.Future<$3.GetAuthorizationStateResponse> getAuthorizationState($pb.ServerContext ctx, $3.GetAuthorizationStateRequest request);
  $async.Future<$3.GetBasicGroupResponse> getBasicGroup($pb.ServerContext ctx, $3.GetBasicGroupRequest request);
  $async.Future<$3.GetBasicGroupFullInfoResponse> getBasicGroupFullInfo($pb.ServerContext ctx, $3.GetBasicGroupFullInfoRequest request);
  $async.Future<$3.GetBlockedUsersResponse> getBlockedUsers($pb.ServerContext ctx, $3.GetBlockedUsersRequest request);
  $async.Future<$3.GetCallbackQueryAnswerResponse> getCallbackQueryAnswer($pb.ServerContext ctx, $3.GetCallbackQueryAnswerRequest request);
  $async.Future<$3.GetChatResponse> getChat($pb.ServerContext ctx, $3.GetChatRequest request);
  $async.Future<$3.GetChatAdministratorsResponse> getChatAdministrators($pb.ServerContext ctx, $3.GetChatAdministratorsRequest request);
  $async.Future<$3.GetChatEventLogResponse> getChatEventLog($pb.ServerContext ctx, $3.GetChatEventLogRequest request);
  $async.Future<$3.GetChatHistoryResponse> getChatHistory($pb.ServerContext ctx, $3.GetChatHistoryRequest request);
  $async.Future<$3.GetChatMemberResponse> getChatMember($pb.ServerContext ctx, $3.GetChatMemberRequest request);
  $async.Future<$3.GetChatMessageByDateResponse> getChatMessageByDate($pb.ServerContext ctx, $3.GetChatMessageByDateRequest request);
  $async.Future<$3.GetChatMessageCountResponse> getChatMessageCount($pb.ServerContext ctx, $3.GetChatMessageCountRequest request);
  $async.Future<$3.GetChatPinnedMessageResponse> getChatPinnedMessage($pb.ServerContext ctx, $3.GetChatPinnedMessageRequest request);
  $async.Future<$3.GetChatReportSpamStateResponse> getChatReportSpamState($pb.ServerContext ctx, $3.GetChatReportSpamStateRequest request);
  $async.Future<$3.GetChatsResponse> getChats($pb.ServerContext ctx, $3.GetChatsRequest request);
  $async.Future<$3.GetConnectedWebsitesResponse> getConnectedWebsites($pb.ServerContext ctx, $3.GetConnectedWebsitesRequest request);
  $async.Future<$3.GetContactsResponse> getContacts($pb.ServerContext ctx, $3.GetContactsRequest request);
  $async.Future<$3.GetCountryCodeResponse> getCountryCode($pb.ServerContext ctx, $3.GetCountryCodeRequest request);
  $async.Future<$3.GetCreatedPublicChatsResponse> getCreatedPublicChats($pb.ServerContext ctx, $3.GetCreatedPublicChatsRequest request);
  $async.Future<$3.GetDeepLinkInfoResponse> getDeepLinkInfo($pb.ServerContext ctx, $3.GetDeepLinkInfoRequest request);
  $async.Future<$3.GetFavoriteStickersResponse> getFavoriteStickers($pb.ServerContext ctx, $3.GetFavoriteStickersRequest request);
  $async.Future<$3.GetFileResponse> getFile($pb.ServerContext ctx, $3.GetFileRequest request);
  $async.Future<$3.GetFileExtensionResponse> getFileExtension($pb.ServerContext ctx, $3.GetFileExtensionRequest request);
  $async.Future<$3.GetFileMimeTypeResponse> getFileMimeType($pb.ServerContext ctx, $3.GetFileMimeTypeRequest request);
  $async.Future<$3.GetGameHighScoresResponse> getGameHighScores($pb.ServerContext ctx, $3.GetGameHighScoresRequest request);
  $async.Future<$3.GetGroupsInCommonResponse> getGroupsInCommon($pb.ServerContext ctx, $3.GetGroupsInCommonRequest request);
  $async.Future<$3.GetImportedContactCountResponse> getImportedContactCount($pb.ServerContext ctx, $3.GetImportedContactCountRequest request);
  $async.Future<$3.GetInlineGameHighScoresResponse> getInlineGameHighScores($pb.ServerContext ctx, $3.GetInlineGameHighScoresRequest request);
  $async.Future<$3.GetInlineQueryResultsResponse> getInlineQueryResults($pb.ServerContext ctx, $3.GetInlineQueryResultsRequest request);
  $async.Future<$3.GetInstalledStickerSetsResponse> getInstalledStickerSets($pb.ServerContext ctx, $3.GetInstalledStickerSetsRequest request);
  $async.Future<$3.GetInviteTextResponse> getInviteText($pb.ServerContext ctx, $3.GetInviteTextRequest request);
  $async.Future<$3.GetLanguagePackStringResponse> getLanguagePackString($pb.ServerContext ctx, $3.GetLanguagePackStringRequest request);
  $async.Future<$3.GetLanguagePackStringsResponse> getLanguagePackStrings($pb.ServerContext ctx, $3.GetLanguagePackStringsRequest request);
  $async.Future<$3.GetLocalizationTargetInfoResponse> getLocalizationTargetInfo($pb.ServerContext ctx, $3.GetLocalizationTargetInfoRequest request);
  $async.Future<$3.GetMapThumbnailFileResponse> getMapThumbnailFile($pb.ServerContext ctx, $3.GetMapThumbnailFileRequest request);
  $async.Future<$3.GetMeResponse> getMe($pb.ServerContext ctx, $3.GetMeRequest request);
  $async.Future<$3.GetMessageResponse> getMessage($pb.ServerContext ctx, $3.GetMessageRequest request);
  $async.Future<$3.GetMessagesResponse> getMessages($pb.ServerContext ctx, $3.GetMessagesRequest request);
  $async.Future<$3.GetNetworkStatisticsResponse> getNetworkStatistics($pb.ServerContext ctx, $3.GetNetworkStatisticsRequest request);
  $async.Future<$3.GetOptionResponse> getOption($pb.ServerContext ctx, $3.GetOptionRequest request);
  $async.Future<$3.GetPassportAuthorizationFormResponse> getPassportAuthorizationForm($pb.ServerContext ctx, $3.GetPassportAuthorizationFormRequest request);
  $async.Future<$3.GetPassportElementResponse> getPassportElement($pb.ServerContext ctx, $3.GetPassportElementRequest request);
  $async.Future<$3.GetPasswordStateResponse> getPasswordState($pb.ServerContext ctx, $3.GetPasswordStateRequest request);
  $async.Future<$3.GetPaymentFormResponse> getPaymentForm($pb.ServerContext ctx, $3.GetPaymentFormRequest request);
  $async.Future<$3.GetPaymentReceiptResponse> getPaymentReceipt($pb.ServerContext ctx, $3.GetPaymentReceiptRequest request);
  $async.Future<$3.GetPreferredCountryLanguageResponse> getPreferredCountryLanguage($pb.ServerContext ctx, $3.GetPreferredCountryLanguageRequest request);
  $async.Future<$3.GetProxiesResponse> getProxies($pb.ServerContext ctx, $3.GetProxiesRequest request);
  $async.Future<$3.GetProxyLinkResponse> getProxyLink($pb.ServerContext ctx, $3.GetProxyLinkRequest request);
  $async.Future<$3.GetPublicMessageLinkResponse> getPublicMessageLink($pb.ServerContext ctx, $3.GetPublicMessageLinkRequest request);
  $async.Future<$3.GetRecentInlineBotsResponse> getRecentInlineBots($pb.ServerContext ctx, $3.GetRecentInlineBotsRequest request);
  $async.Future<$3.GetRecentStickersResponse> getRecentStickers($pb.ServerContext ctx, $3.GetRecentStickersRequest request);
  $async.Future<$3.GetRecentlyVisitedTMeUrlsResponse> getRecentlyVisitedTMeUrls($pb.ServerContext ctx, $3.GetRecentlyVisitedTMeUrlsRequest request);
  $async.Future<$3.GetRecoveryEmailAddressResponse> getRecoveryEmailAddress($pb.ServerContext ctx, $3.GetRecoveryEmailAddressRequest request);
  $async.Future<$3.GetRemoteFileResponse> getRemoteFile($pb.ServerContext ctx, $3.GetRemoteFileRequest request);
  $async.Future<$3.GetRepliedMessageResponse> getRepliedMessage($pb.ServerContext ctx, $3.GetRepliedMessageRequest request);
  $async.Future<$3.GetSavedAnimationsResponse> getSavedAnimations($pb.ServerContext ctx, $3.GetSavedAnimationsRequest request);
  $async.Future<$3.GetSavedOrderInfoResponse> getSavedOrderInfo($pb.ServerContext ctx, $3.GetSavedOrderInfoRequest request);
  $async.Future<$3.GetScopeNotificationSettingsResponse> getScopeNotificationSettings($pb.ServerContext ctx, $3.GetScopeNotificationSettingsRequest request);
  $async.Future<$3.GetSecretChatResponse> getSecretChat($pb.ServerContext ctx, $3.GetSecretChatRequest request);
  $async.Future<$3.GetStickerEmojisResponse> getStickerEmojis($pb.ServerContext ctx, $3.GetStickerEmojisRequest request);
  $async.Future<$3.GetStickerSetResponse> getStickerSet($pb.ServerContext ctx, $3.GetStickerSetRequest request);
  $async.Future<$3.GetStickersResponse> getStickers($pb.ServerContext ctx, $3.GetStickersRequest request);
  $async.Future<$3.GetStorageStatisticsResponse> getStorageStatistics($pb.ServerContext ctx, $3.GetStorageStatisticsRequest request);
  $async.Future<$3.GetStorageStatisticsFastResponse> getStorageStatisticsFast($pb.ServerContext ctx, $3.GetStorageStatisticsFastRequest request);
  $async.Future<$3.GetSupergroupResponse> getSupergroup($pb.ServerContext ctx, $3.GetSupergroupRequest request);
  $async.Future<$3.GetSupergroupFullInfoResponse> getSupergroupFullInfo($pb.ServerContext ctx, $3.GetSupergroupFullInfoRequest request);
  $async.Future<$3.GetSupergroupMembersResponse> getSupergroupMembers($pb.ServerContext ctx, $3.GetSupergroupMembersRequest request);
  $async.Future<$3.GetSupportUserResponse> getSupportUser($pb.ServerContext ctx, $3.GetSupportUserRequest request);
  $async.Future<$3.GetTemporaryPasswordStateResponse> getTemporaryPasswordState($pb.ServerContext ctx, $3.GetTemporaryPasswordStateRequest request);
  $async.Future<$3.GetTextEntitiesResponse> getTextEntities($pb.ServerContext ctx, $3.GetTextEntitiesRequest request);
  $async.Future<$3.GetTopChatsResponse> getTopChats($pb.ServerContext ctx, $3.GetTopChatsRequest request);
  $async.Future<$3.GetTrendingStickerSetsResponse> getTrendingStickerSets($pb.ServerContext ctx, $3.GetTrendingStickerSetsRequest request);
  $async.Future<$3.GetUserResponse> getUser($pb.ServerContext ctx, $3.GetUserRequest request);
  $async.Future<$3.GetUserFullInfoResponse> getUserFullInfo($pb.ServerContext ctx, $3.GetUserFullInfoRequest request);
  $async.Future<$3.GetUserPrivacySettingRulesResponse> getUserPrivacySettingRules($pb.ServerContext ctx, $3.GetUserPrivacySettingRulesRequest request);
  $async.Future<$3.GetUserProfilePhotosResponse> getUserProfilePhotos($pb.ServerContext ctx, $3.GetUserProfilePhotosRequest request);
  $async.Future<$3.GetWallpapersResponse> getWallpapers($pb.ServerContext ctx, $3.GetWallpapersRequest request);
  $async.Future<$3.GetWebPageInstantViewResponse> getWebPageInstantView($pb.ServerContext ctx, $3.GetWebPageInstantViewRequest request);
  $async.Future<$3.GetWebPagePreviewResponse> getWebPagePreview($pb.ServerContext ctx, $3.GetWebPagePreviewRequest request);
  $async.Future<$3.ImportContactsResponse> importContacts($pb.ServerContext ctx, $3.ImportContactsRequest request);
  $async.Future<$3.JoinChatResponse> joinChat($pb.ServerContext ctx, $3.JoinChatRequest request);
  $async.Future<$3.JoinChatByInviteLinkResponse> joinChatByInviteLink($pb.ServerContext ctx, $3.JoinChatByInviteLinkRequest request);
  $async.Future<$3.LeaveChatResponse> leaveChat($pb.ServerContext ctx, $3.LeaveChatRequest request);
  $async.Future<$3.LogOutResponse> logOut($pb.ServerContext ctx, $3.LogOutRequest request);
  $async.Future<$3.OpenChatResponse> openChat($pb.ServerContext ctx, $3.OpenChatRequest request);
  $async.Future<$3.OpenMessageContentResponse> openMessageContent($pb.ServerContext ctx, $3.OpenMessageContentRequest request);
  $async.Future<$3.OptimizeStorageResponse> optimizeStorage($pb.ServerContext ctx, $3.OptimizeStorageRequest request);
  $async.Future<$3.ParseTextEntitiesResponse> parseTextEntities($pb.ServerContext ctx, $3.ParseTextEntitiesRequest request);
  $async.Future<$3.PinSupergroupMessageResponse> pinSupergroupMessage($pb.ServerContext ctx, $3.PinSupergroupMessageRequest request);
  $async.Future<$3.PingProxyResponse> pingProxy($pb.ServerContext ctx, $3.PingProxyRequest request);
  $async.Future<$3.ProcessDcUpdateResponse> processDcUpdate($pb.ServerContext ctx, $3.ProcessDcUpdateRequest request);
  $async.Future<$3.ReadAllChatMentionsResponse> readAllChatMentions($pb.ServerContext ctx, $3.ReadAllChatMentionsRequest request);
  $async.Future<$3.RecoverAuthenticationPasswordResponse> recoverAuthenticationPassword($pb.ServerContext ctx, $3.RecoverAuthenticationPasswordRequest request);
  $async.Future<$3.RecoverPasswordResponse> recoverPassword($pb.ServerContext ctx, $3.RecoverPasswordRequest request);
  $async.Future<$3.RegisterDeviceResponse> registerDevice($pb.ServerContext ctx, $3.RegisterDeviceRequest request);
  $async.Future<$3.RemoveContactsResponse> removeContacts($pb.ServerContext ctx, $3.RemoveContactsRequest request);
  $async.Future<$3.RemoveFavoriteStickerResponse> removeFavoriteSticker($pb.ServerContext ctx, $3.RemoveFavoriteStickerRequest request);
  $async.Future<$3.RemoveProxyResponse> removeProxy($pb.ServerContext ctx, $3.RemoveProxyRequest request);
  $async.Future<$3.RemoveRecentHashtagResponse> removeRecentHashtag($pb.ServerContext ctx, $3.RemoveRecentHashtagRequest request);
  $async.Future<$3.RemoveRecentStickerResponse> removeRecentSticker($pb.ServerContext ctx, $3.RemoveRecentStickerRequest request);
  $async.Future<$3.RemoveRecentlyFoundChatResponse> removeRecentlyFoundChat($pb.ServerContext ctx, $3.RemoveRecentlyFoundChatRequest request);
  $async.Future<$3.RemoveSavedAnimationResponse> removeSavedAnimation($pb.ServerContext ctx, $3.RemoveSavedAnimationRequest request);
  $async.Future<$3.RemoveStickerFromSetResponse> removeStickerFromSet($pb.ServerContext ctx, $3.RemoveStickerFromSetRequest request);
  $async.Future<$3.RemoveTopChatResponse> removeTopChat($pb.ServerContext ctx, $3.RemoveTopChatRequest request);
  $async.Future<$3.ReorderInstalledStickerSetsResponse> reorderInstalledStickerSets($pb.ServerContext ctx, $3.ReorderInstalledStickerSetsRequest request);
  $async.Future<$3.ReportChatResponse> reportChat($pb.ServerContext ctx, $3.ReportChatRequest request);
  $async.Future<$3.ReportSupergroupSpamResponse> reportSupergroupSpam($pb.ServerContext ctx, $3.ReportSupergroupSpamRequest request);
  $async.Future<$3.RequestAuthenticationPasswordRecoveryResponse> requestAuthenticationPasswordRecovery($pb.ServerContext ctx, $3.RequestAuthenticationPasswordRecoveryRequest request);
  $async.Future<$3.RequestPasswordRecoveryResponse> requestPasswordRecovery($pb.ServerContext ctx, $3.RequestPasswordRecoveryRequest request);
  $async.Future<$3.ResendAuthenticationCodeResponse> resendAuthenticationCode($pb.ServerContext ctx, $3.ResendAuthenticationCodeRequest request);
  $async.Future<$3.ResendChangePhoneNumberCodeResponse> resendChangePhoneNumberCode($pb.ServerContext ctx, $3.ResendChangePhoneNumberCodeRequest request);
  $async.Future<$3.ResendEmailAddressVerificationCodeResponse> resendEmailAddressVerificationCode($pb.ServerContext ctx, $3.ResendEmailAddressVerificationCodeRequest request);
  $async.Future<$3.ResendPhoneNumberConfirmationCodeResponse> resendPhoneNumberConfirmationCode($pb.ServerContext ctx, $3.ResendPhoneNumberConfirmationCodeRequest request);
  $async.Future<$3.ResendPhoneNumberVerificationCodeResponse> resendPhoneNumberVerificationCode($pb.ServerContext ctx, $3.ResendPhoneNumberVerificationCodeRequest request);
  $async.Future<$3.ResetAllNotificationSettingsResponse> resetAllNotificationSettings($pb.ServerContext ctx, $3.ResetAllNotificationSettingsRequest request);
  $async.Future<$3.ResetNetworkStatisticsResponse> resetNetworkStatistics($pb.ServerContext ctx, $3.ResetNetworkStatisticsRequest request);
  $async.Future<$3.SearchCallMessagesResponse> searchCallMessages($pb.ServerContext ctx, $3.SearchCallMessagesRequest request);
  $async.Future<$3.SearchChatMembersResponse> searchChatMembers($pb.ServerContext ctx, $3.SearchChatMembersRequest request);
  $async.Future<$3.SearchChatMessagesResponse> searchChatMessages($pb.ServerContext ctx, $3.SearchChatMessagesRequest request);
  $async.Future<$3.SearchChatRecentLocationMessagesResponse> searchChatRecentLocationMessages($pb.ServerContext ctx, $3.SearchChatRecentLocationMessagesRequest request);
  $async.Future<$3.SearchChatsResponse> searchChats($pb.ServerContext ctx, $3.SearchChatsRequest request);
  $async.Future<$3.SearchChatsOnServerResponse> searchChatsOnServer($pb.ServerContext ctx, $3.SearchChatsOnServerRequest request);
  $async.Future<$3.SearchContactsResponse> searchContacts($pb.ServerContext ctx, $3.SearchContactsRequest request);
  $async.Future<$3.SearchHashtagsResponse> searchHashtags($pb.ServerContext ctx, $3.SearchHashtagsRequest request);
  $async.Future<$3.SearchInstalledStickerSetsResponse> searchInstalledStickerSets($pb.ServerContext ctx, $3.SearchInstalledStickerSetsRequest request);
  $async.Future<$3.SearchMessagesResponse> searchMessages($pb.ServerContext ctx, $3.SearchMessagesRequest request);
  $async.Future<$3.SearchPublicChatResponse> searchPublicChat($pb.ServerContext ctx, $3.SearchPublicChatRequest request);
  $async.Future<$3.SearchPublicChatsResponse> searchPublicChats($pb.ServerContext ctx, $3.SearchPublicChatsRequest request);
  $async.Future<$3.SearchSecretMessagesResponse> searchSecretMessages($pb.ServerContext ctx, $3.SearchSecretMessagesRequest request);
  $async.Future<$3.SearchStickerSetResponse> searchStickerSet($pb.ServerContext ctx, $3.SearchStickerSetRequest request);
  $async.Future<$3.SearchStickerSetsResponse> searchStickerSets($pb.ServerContext ctx, $3.SearchStickerSetsRequest request);
  $async.Future<$3.SearchStickersResponse> searchStickers($pb.ServerContext ctx, $3.SearchStickersRequest request);
  $async.Future<$3.SendBotStartMessageResponse> sendBotStartMessage($pb.ServerContext ctx, $3.SendBotStartMessageRequest request);
  $async.Future<$3.SendCallDebugInformationResponse> sendCallDebugInformation($pb.ServerContext ctx, $3.SendCallDebugInformationRequest request);
  $async.Future<$3.SendCallRatingResponse> sendCallRating($pb.ServerContext ctx, $3.SendCallRatingRequest request);
  $async.Future<$3.SendChatActionResponse> sendChatAction($pb.ServerContext ctx, $3.SendChatActionRequest request);
  $async.Future<$3.SendChatScreenshotTakenNotificationResponse> sendChatScreenshotTakenNotification($pb.ServerContext ctx, $3.SendChatScreenshotTakenNotificationRequest request);
  $async.Future<$3.SendChatSetTTLMessageResponse> sendChatSetTTLMessage($pb.ServerContext ctx, $3.SendChatSetTTLMessageRequest request);
  $async.Future<$3.SendCustomRequestResponse> sendCustomRequest($pb.ServerContext ctx, $3.SendCustomRequestRequest request);
  $async.Future<$3.SendEmailAddressVerificationCodeResponse> sendEmailAddressVerificationCode($pb.ServerContext ctx, $3.SendEmailAddressVerificationCodeRequest request);
  $async.Future<$3.SendInlineQueryResultMessageResponse> sendInlineQueryResultMessage($pb.ServerContext ctx, $3.SendInlineQueryResultMessageRequest request);
  $async.Future<$3.SendMessageResponse> sendMessage($pb.ServerContext ctx, $3.SendMessageRequest request);
  $async.Future<$3.SendMessageAlbumResponse> sendMessageAlbum($pb.ServerContext ctx, $3.SendMessageAlbumRequest request);
  $async.Future<$3.SendPassportAuthorizationFormResponse> sendPassportAuthorizationForm($pb.ServerContext ctx, $3.SendPassportAuthorizationFormRequest request);
  $async.Future<$3.SendPaymentFormResponse> sendPaymentForm($pb.ServerContext ctx, $3.SendPaymentFormRequest request);
  $async.Future<$3.SendPhoneNumberConfirmationCodeResponse> sendPhoneNumberConfirmationCode($pb.ServerContext ctx, $3.SendPhoneNumberConfirmationCodeRequest request);
  $async.Future<$3.SendPhoneNumberVerificationCodeResponse> sendPhoneNumberVerificationCode($pb.ServerContext ctx, $3.SendPhoneNumberVerificationCodeRequest request);
  $async.Future<$3.SetAccountTTLResponse> setAccountTTL($pb.ServerContext ctx, $3.SetAccountTTLRequest request);
  $async.Future<$3.SetAlarmResponse> setAlarm($pb.ServerContext ctx, $3.SetAlarmRequest request);
  $async.Future<$3.SetAuthenticationPhoneNumberResponse> setAuthenticationPhoneNumber($pb.ServerContext ctx, $3.SetAuthenticationPhoneNumberRequest request);
  $async.Future<$3.SetBioResponse> setBio($pb.ServerContext ctx, $3.SetBioRequest request);
  $async.Future<$3.SetBotUpdatesStatusResponse> setBotUpdatesStatus($pb.ServerContext ctx, $3.SetBotUpdatesStatusRequest request);
  $async.Future<$3.SetChatClientDataResponse> setChatClientData($pb.ServerContext ctx, $3.SetChatClientDataRequest request);
  $async.Future<$3.SetChatDraftMessageResponse> setChatDraftMessage($pb.ServerContext ctx, $3.SetChatDraftMessageRequest request);
  $async.Future<$3.SetChatMemberStatusResponse> setChatMemberStatus($pb.ServerContext ctx, $3.SetChatMemberStatusRequest request);
  $async.Future<$3.SetChatNotificationSettingsResponse> setChatNotificationSettings($pb.ServerContext ctx, $3.SetChatNotificationSettingsRequest request);
  $async.Future<$3.SetChatPhotoResponse> setChatPhoto($pb.ServerContext ctx, $3.SetChatPhotoRequest request);
  $async.Future<$3.SetChatTitleResponse> setChatTitle($pb.ServerContext ctx, $3.SetChatTitleRequest request);
  $async.Future<$3.SetCustomLanguagePackResponse> setCustomLanguagePack($pb.ServerContext ctx, $3.SetCustomLanguagePackRequest request);
  $async.Future<$3.SetCustomLanguagePackStringResponse> setCustomLanguagePackString($pb.ServerContext ctx, $3.SetCustomLanguagePackStringRequest request);
  $async.Future<$3.SetDatabaseEncryptionKeyResponse> setDatabaseEncryptionKey($pb.ServerContext ctx, $3.SetDatabaseEncryptionKeyRequest request);
  $async.Future<$3.SetFileGenerationProgressResponse> setFileGenerationProgress($pb.ServerContext ctx, $3.SetFileGenerationProgressRequest request);
  $async.Future<$3.SetGameScoreResponse> setGameScore($pb.ServerContext ctx, $3.SetGameScoreRequest request);
  $async.Future<$3.SetInlineGameScoreResponse> setInlineGameScore($pb.ServerContext ctx, $3.SetInlineGameScoreRequest request);
  $async.Future<$3.SetNameResponse> setName($pb.ServerContext ctx, $3.SetNameRequest request);
  $async.Future<$3.SetNetworkTypeResponse> setNetworkType($pb.ServerContext ctx, $3.SetNetworkTypeRequest request);
  $async.Future<$3.SetOptionResponse> setOption($pb.ServerContext ctx, $3.SetOptionRequest request);
  $async.Future<$3.SetPassportElementResponse> setPassportElement($pb.ServerContext ctx, $3.SetPassportElementRequest request);
  $async.Future<$3.SetPassportElementErrorsResponse> setPassportElementErrors($pb.ServerContext ctx, $3.SetPassportElementErrorsRequest request);
  $async.Future<$3.SetPasswordResponse> setPassword($pb.ServerContext ctx, $3.SetPasswordRequest request);
  $async.Future<$3.SetPinnedChatsResponse> setPinnedChats($pb.ServerContext ctx, $3.SetPinnedChatsRequest request);
  $async.Future<$3.SetProfilePhotoResponse> setProfilePhoto($pb.ServerContext ctx, $3.SetProfilePhotoRequest request);
  $async.Future<$3.SetRecoveryEmailAddressResponse> setRecoveryEmailAddress($pb.ServerContext ctx, $3.SetRecoveryEmailAddressRequest request);
  $async.Future<$3.SetScopeNotificationSettingsResponse> setScopeNotificationSettings($pb.ServerContext ctx, $3.SetScopeNotificationSettingsRequest request);
  $async.Future<$3.SetStickerPositionInSetResponse> setStickerPositionInSet($pb.ServerContext ctx, $3.SetStickerPositionInSetRequest request);
  $async.Future<$3.SetSupergroupDescriptionResponse> setSupergroupDescription($pb.ServerContext ctx, $3.SetSupergroupDescriptionRequest request);
  $async.Future<$3.SetSupergroupStickerSetResponse> setSupergroupStickerSet($pb.ServerContext ctx, $3.SetSupergroupStickerSetRequest request);
  $async.Future<$3.SetSupergroupUsernameResponse> setSupergroupUsername($pb.ServerContext ctx, $3.SetSupergroupUsernameRequest request);
  $async.Future<$3.SetTdlibParametersResponse> setTdlibParameters($pb.ServerContext ctx, $3.SetTdlibParametersRequest request);
  $async.Future<$3.SetUserPrivacySettingRulesResponse> setUserPrivacySettingRules($pb.ServerContext ctx, $3.SetUserPrivacySettingRulesRequest request);
  $async.Future<$3.SetUsernameResponse> setUsername($pb.ServerContext ctx, $3.SetUsernameRequest request);
  $async.Future<$3.TerminateAllOtherSessionsResponse> terminateAllOtherSessions($pb.ServerContext ctx, $3.TerminateAllOtherSessionsRequest request);
  $async.Future<$3.TerminateSessionResponse> terminateSession($pb.ServerContext ctx, $3.TerminateSessionRequest request);
  $async.Future<$3.TestCallBytesResponse> testCallBytes($pb.ServerContext ctx, $3.TestCallBytesRequest request);
  $async.Future<$3.TestCallEmptyResponse> testCallEmpty($pb.ServerContext ctx, $3.TestCallEmptyRequest request);
  $async.Future<$3.TestCallStringResponse> testCallString($pb.ServerContext ctx, $3.TestCallStringRequest request);
  $async.Future<$3.TestCallVectorIntResponse> testCallVectorInt($pb.ServerContext ctx, $3.TestCallVectorIntRequest request);
  $async.Future<$3.TestCallVectorIntObjectResponse> testCallVectorIntObject($pb.ServerContext ctx, $3.TestCallVectorIntObjectRequest request);
  $async.Future<$3.TestCallVectorStringResponse> testCallVectorString($pb.ServerContext ctx, $3.TestCallVectorStringRequest request);
  $async.Future<$3.TestCallVectorStringObjectResponse> testCallVectorStringObject($pb.ServerContext ctx, $3.TestCallVectorStringObjectRequest request);
  $async.Future<$3.TestGetDifferenceResponse> testGetDifference($pb.ServerContext ctx, $3.TestGetDifferenceRequest request);
  $async.Future<$3.TestNetworkResponse> testNetwork($pb.ServerContext ctx, $3.TestNetworkRequest request);
  $async.Future<$3.TestSquareIntResponse> testSquareInt($pb.ServerContext ctx, $3.TestSquareIntRequest request);
  $async.Future<$3.TestUseErrorResponse> testUseError($pb.ServerContext ctx, $3.TestUseErrorRequest request);
  $async.Future<$3.TestUseUpdateResponse> testUseUpdate($pb.ServerContext ctx, $3.TestUseUpdateRequest request);
  $async.Future<$3.ToggleBasicGroupAdministratorsResponse> toggleBasicGroupAdministrators($pb.ServerContext ctx, $3.ToggleBasicGroupAdministratorsRequest request);
  $async.Future<$3.ToggleChatDefaultDisableNotificationResponse> toggleChatDefaultDisableNotification($pb.ServerContext ctx, $3.ToggleChatDefaultDisableNotificationRequest request);
  $async.Future<$3.ToggleChatIsMarkedAsUnreadResponse> toggleChatIsMarkedAsUnread($pb.ServerContext ctx, $3.ToggleChatIsMarkedAsUnreadRequest request);
  $async.Future<$3.ToggleChatIsPinnedResponse> toggleChatIsPinned($pb.ServerContext ctx, $3.ToggleChatIsPinnedRequest request);
  $async.Future<$3.ToggleSupergroupInvitesResponse> toggleSupergroupInvites($pb.ServerContext ctx, $3.ToggleSupergroupInvitesRequest request);
  $async.Future<$3.ToggleSupergroupIsAllHistoryAvailableResponse> toggleSupergroupIsAllHistoryAvailable($pb.ServerContext ctx, $3.ToggleSupergroupIsAllHistoryAvailableRequest request);
  $async.Future<$3.ToggleSupergroupSignMessagesResponse> toggleSupergroupSignMessages($pb.ServerContext ctx, $3.ToggleSupergroupSignMessagesRequest request);
  $async.Future<$3.UnblockUserResponse> unblockUser($pb.ServerContext ctx, $3.UnblockUserRequest request);
  $async.Future<$3.UnpinSupergroupMessageResponse> unpinSupergroupMessage($pb.ServerContext ctx, $3.UnpinSupergroupMessageRequest request);
  $async.Future<$3.UpgradeBasicGroupChatToSupergroupChatResponse> upgradeBasicGroupChatToSupergroupChat($pb.ServerContext ctx, $3.UpgradeBasicGroupChatToSupergroupChatRequest request);
  $async.Future<$3.UploadFileResponse> uploadFile($pb.ServerContext ctx, $3.UploadFileRequest request);
  $async.Future<$3.UploadStickerFileResponse> uploadStickerFile($pb.ServerContext ctx, $3.UploadStickerFileRequest request);
  $async.Future<$3.ValidateOrderInfoResponse> validateOrderInfo($pb.ServerContext ctx, $3.ValidateOrderInfoRequest request);
  $async.Future<$3.ViewMessagesResponse> viewMessages($pb.ServerContext ctx, $3.ViewMessagesRequest request);
  $async.Future<$3.ViewTrendingStickerSetsResponse> viewTrendingStickerSets($pb.ServerContext ctx, $3.ViewTrendingStickerSetsRequest request);

  $pb.GeneratedMessage createRequest($core.String method) {
    switch (method) {
      case 'AcceptCall': return $3.AcceptCallRequest();
      case 'AcceptTermsOfService': return $3.AcceptTermsOfServiceRequest();
      case 'AddChatMember': return $3.AddChatMemberRequest();
      case 'AddChatMembers': return $3.AddChatMembersRequest();
      case 'AddFavoriteSticker': return $3.AddFavoriteStickerRequest();
      case 'AddLocalMessage': return $3.AddLocalMessageRequest();
      case 'AddNetworkStatistics': return $3.AddNetworkStatisticsRequest();
      case 'AddProxy': return $3.AddProxyRequest();
      case 'AddRecentSticker': return $3.AddRecentStickerRequest();
      case 'AddRecentlyFoundChat': return $3.AddRecentlyFoundChatRequest();
      case 'AddSavedAnimation': return $3.AddSavedAnimationRequest();
      case 'AddStickerToSet': return $3.AddStickerToSetRequest();
      case 'AnswerCallbackQuery': return $3.AnswerCallbackQueryRequest();
      case 'AnswerCustomQuery': return $3.AnswerCustomQueryRequest();
      case 'AnswerInlineQuery': return $3.AnswerInlineQueryRequest();
      case 'AnswerPreCheckoutQuery': return $3.AnswerPreCheckoutQueryRequest();
      case 'AnswerShippingQuery': return $3.AnswerShippingQueryRequest();
      case 'BlockUser': return $3.BlockUserRequest();
      case 'CancelDownloadFile': return $3.CancelDownloadFileRequest();
      case 'CancelUploadFile': return $3.CancelUploadFileRequest();
      case 'ChangeChatReportSpamState': return $3.ChangeChatReportSpamStateRequest();
      case 'ChangeImportedContacts': return $3.ChangeImportedContactsRequest();
      case 'ChangePhoneNumber': return $3.ChangePhoneNumberRequest();
      case 'ChangeStickerSet': return $3.ChangeStickerSetRequest();
      case 'CheckAuthenticationBotToken': return $3.CheckAuthenticationBotTokenRequest();
      case 'CheckAuthenticationCode': return $3.CheckAuthenticationCodeRequest();
      case 'CheckAuthenticationPassword': return $3.CheckAuthenticationPasswordRequest();
      case 'CheckChangePhoneNumberCode': return $3.CheckChangePhoneNumberCodeRequest();
      case 'CheckChatInviteLink': return $3.CheckChatInviteLinkRequest();
      case 'CheckChatUsername': return $3.CheckChatUsernameRequest();
      case 'CheckDatabaseEncryptionKey': return $3.CheckDatabaseEncryptionKeyRequest();
      case 'CheckEmailAddressVerificationCode': return $3.CheckEmailAddressVerificationCodeRequest();
      case 'CheckPhoneNumberConfirmationCode': return $3.CheckPhoneNumberConfirmationCodeRequest();
      case 'CheckPhoneNumberVerificationCode': return $3.CheckPhoneNumberVerificationCodeRequest();
      case 'CleanFileName': return $3.CleanFileNameRequest();
      case 'ClearAllDraftMessages': return $3.ClearAllDraftMessagesRequest();
      case 'ClearImportedContacts': return $3.ClearImportedContactsRequest();
      case 'ClearRecentStickers': return $3.ClearRecentStickersRequest();
      case 'ClearRecentlyFoundChats': return $3.ClearRecentlyFoundChatsRequest();
      case 'Close': return $3.CloseRequest();
      case 'CloseChat': return $3.CloseChatRequest();
      case 'CloseSecretChat': return $3.CloseSecretChatRequest();
      case 'CreateBasicGroupChat': return $3.CreateBasicGroupChatRequest();
      case 'CreateCall': return $3.CreateCallRequest();
      case 'CreateNewBasicGroupChat': return $3.CreateNewBasicGroupChatRequest();
      case 'CreateNewSecretChat': return $3.CreateNewSecretChatRequest();
      case 'CreateNewStickerSet': return $3.CreateNewStickerSetRequest();
      case 'CreateNewSupergroupChat': return $3.CreateNewSupergroupChatRequest();
      case 'CreatePrivateChat': return $3.CreatePrivateChatRequest();
      case 'CreateSecretChat': return $3.CreateSecretChatRequest();
      case 'CreateSupergroupChat': return $3.CreateSupergroupChatRequest();
      case 'CreateTemporaryPassword': return $3.CreateTemporaryPasswordRequest();
      case 'DeleteAccount': return $3.DeleteAccountRequest();
      case 'DeleteChatHistory': return $3.DeleteChatHistoryRequest();
      case 'DeleteChatMessagesFromUser': return $3.DeleteChatMessagesFromUserRequest();
      case 'DeleteChatReplyMarkup': return $3.DeleteChatReplyMarkupRequest();
      case 'DeleteFile': return $3.DeleteFileRequest();
      case 'DeleteLanguagePack': return $3.DeleteLanguagePackRequest();
      case 'DeleteMessages': return $3.DeleteMessagesRequest();
      case 'DeletePassportElement': return $3.DeletePassportElementRequest();
      case 'DeleteProfilePhoto': return $3.DeleteProfilePhotoRequest();
      case 'DeleteSavedCredentials': return $3.DeleteSavedCredentialsRequest();
      case 'DeleteSavedOrderInfo': return $3.DeleteSavedOrderInfoRequest();
      case 'DeleteSupergroup': return $3.DeleteSupergroupRequest();
      case 'Destroy': return $3.DestroyRequest();
      case 'DisableProxy': return $3.DisableProxyRequest();
      case 'DiscardCall': return $3.DiscardCallRequest();
      case 'DisconnectAllWebsites': return $3.DisconnectAllWebsitesRequest();
      case 'DisconnectWebsite': return $3.DisconnectWebsiteRequest();
      case 'DownloadFile': return $3.DownloadFileRequest();
      case 'EditCustomLanguagePackInfo': return $3.EditCustomLanguagePackInfoRequest();
      case 'EditInlineMessageCaption': return $3.EditInlineMessageCaptionRequest();
      case 'EditInlineMessageLiveLocation': return $3.EditInlineMessageLiveLocationRequest();
      case 'EditInlineMessageMedia': return $3.EditInlineMessageMediaRequest();
      case 'EditInlineMessageReplyMarkup': return $3.EditInlineMessageReplyMarkupRequest();
      case 'EditInlineMessageText': return $3.EditInlineMessageTextRequest();
      case 'EditMessageCaption': return $3.EditMessageCaptionRequest();
      case 'EditMessageLiveLocation': return $3.EditMessageLiveLocationRequest();
      case 'EditMessageMedia': return $3.EditMessageMediaRequest();
      case 'EditMessageReplyMarkup': return $3.EditMessageReplyMarkupRequest();
      case 'EditMessageText': return $3.EditMessageTextRequest();
      case 'EditProxy': return $3.EditProxyRequest();
      case 'EnableProxy': return $3.EnableProxyRequest();
      case 'FinishFileGeneration': return $3.FinishFileGenerationRequest();
      case 'ForwardMessages': return $3.ForwardMessagesRequest();
      case 'GenerateChatInviteLink': return $3.GenerateChatInviteLinkRequest();
      case 'GetAccountTTL': return $3.GetAccountTTLRequest();
      case 'GetActiveLiveLocationMessages': return $3.GetActiveLiveLocationMessagesRequest();
      case 'GetActiveSessions': return $3.GetActiveSessionsRequest();
      case 'GetAllPassportElements': return $3.GetAllPassportElementsRequest();
      case 'GetArchivedStickerSets': return $3.GetArchivedStickerSetsRequest();
      case 'GetAttachedStickerSets': return $3.GetAttachedStickerSetsRequest();
      case 'GetAuthorizationState': return $3.GetAuthorizationStateRequest();
      case 'GetBasicGroup': return $3.GetBasicGroupRequest();
      case 'GetBasicGroupFullInfo': return $3.GetBasicGroupFullInfoRequest();
      case 'GetBlockedUsers': return $3.GetBlockedUsersRequest();
      case 'GetCallbackQueryAnswer': return $3.GetCallbackQueryAnswerRequest();
      case 'GetChat': return $3.GetChatRequest();
      case 'GetChatAdministrators': return $3.GetChatAdministratorsRequest();
      case 'GetChatEventLog': return $3.GetChatEventLogRequest();
      case 'GetChatHistory': return $3.GetChatHistoryRequest();
      case 'GetChatMember': return $3.GetChatMemberRequest();
      case 'GetChatMessageByDate': return $3.GetChatMessageByDateRequest();
      case 'GetChatMessageCount': return $3.GetChatMessageCountRequest();
      case 'GetChatPinnedMessage': return $3.GetChatPinnedMessageRequest();
      case 'GetChatReportSpamState': return $3.GetChatReportSpamStateRequest();
      case 'GetChats': return $3.GetChatsRequest();
      case 'GetConnectedWebsites': return $3.GetConnectedWebsitesRequest();
      case 'GetContacts': return $3.GetContactsRequest();
      case 'GetCountryCode': return $3.GetCountryCodeRequest();
      case 'GetCreatedPublicChats': return $3.GetCreatedPublicChatsRequest();
      case 'GetDeepLinkInfo': return $3.GetDeepLinkInfoRequest();
      case 'GetFavoriteStickers': return $3.GetFavoriteStickersRequest();
      case 'GetFile': return $3.GetFileRequest();
      case 'GetFileExtension': return $3.GetFileExtensionRequest();
      case 'GetFileMimeType': return $3.GetFileMimeTypeRequest();
      case 'GetGameHighScores': return $3.GetGameHighScoresRequest();
      case 'GetGroupsInCommon': return $3.GetGroupsInCommonRequest();
      case 'GetImportedContactCount': return $3.GetImportedContactCountRequest();
      case 'GetInlineGameHighScores': return $3.GetInlineGameHighScoresRequest();
      case 'GetInlineQueryResults': return $3.GetInlineQueryResultsRequest();
      case 'GetInstalledStickerSets': return $3.GetInstalledStickerSetsRequest();
      case 'GetInviteText': return $3.GetInviteTextRequest();
      case 'GetLanguagePackString': return $3.GetLanguagePackStringRequest();
      case 'GetLanguagePackStrings': return $3.GetLanguagePackStringsRequest();
      case 'GetLocalizationTargetInfo': return $3.GetLocalizationTargetInfoRequest();
      case 'GetMapThumbnailFile': return $3.GetMapThumbnailFileRequest();
      case 'GetMe': return $3.GetMeRequest();
      case 'GetMessage': return $3.GetMessageRequest();
      case 'GetMessages': return $3.GetMessagesRequest();
      case 'GetNetworkStatistics': return $3.GetNetworkStatisticsRequest();
      case 'GetOption': return $3.GetOptionRequest();
      case 'GetPassportAuthorizationForm': return $3.GetPassportAuthorizationFormRequest();
      case 'GetPassportElement': return $3.GetPassportElementRequest();
      case 'GetPasswordState': return $3.GetPasswordStateRequest();
      case 'GetPaymentForm': return $3.GetPaymentFormRequest();
      case 'GetPaymentReceipt': return $3.GetPaymentReceiptRequest();
      case 'GetPreferredCountryLanguage': return $3.GetPreferredCountryLanguageRequest();
      case 'GetProxies': return $3.GetProxiesRequest();
      case 'GetProxyLink': return $3.GetProxyLinkRequest();
      case 'GetPublicMessageLink': return $3.GetPublicMessageLinkRequest();
      case 'GetRecentInlineBots': return $3.GetRecentInlineBotsRequest();
      case 'GetRecentStickers': return $3.GetRecentStickersRequest();
      case 'GetRecentlyVisitedTMeUrls': return $3.GetRecentlyVisitedTMeUrlsRequest();
      case 'GetRecoveryEmailAddress': return $3.GetRecoveryEmailAddressRequest();
      case 'GetRemoteFile': return $3.GetRemoteFileRequest();
      case 'GetRepliedMessage': return $3.GetRepliedMessageRequest();
      case 'GetSavedAnimations': return $3.GetSavedAnimationsRequest();
      case 'GetSavedOrderInfo': return $3.GetSavedOrderInfoRequest();
      case 'GetScopeNotificationSettings': return $3.GetScopeNotificationSettingsRequest();
      case 'GetSecretChat': return $3.GetSecretChatRequest();
      case 'GetStickerEmojis': return $3.GetStickerEmojisRequest();
      case 'GetStickerSet': return $3.GetStickerSetRequest();
      case 'GetStickers': return $3.GetStickersRequest();
      case 'GetStorageStatistics': return $3.GetStorageStatisticsRequest();
      case 'GetStorageStatisticsFast': return $3.GetStorageStatisticsFastRequest();
      case 'GetSupergroup': return $3.GetSupergroupRequest();
      case 'GetSupergroupFullInfo': return $3.GetSupergroupFullInfoRequest();
      case 'GetSupergroupMembers': return $3.GetSupergroupMembersRequest();
      case 'GetSupportUser': return $3.GetSupportUserRequest();
      case 'GetTemporaryPasswordState': return $3.GetTemporaryPasswordStateRequest();
      case 'GetTextEntities': return $3.GetTextEntitiesRequest();
      case 'GetTopChats': return $3.GetTopChatsRequest();
      case 'GetTrendingStickerSets': return $3.GetTrendingStickerSetsRequest();
      case 'GetUser': return $3.GetUserRequest();
      case 'GetUserFullInfo': return $3.GetUserFullInfoRequest();
      case 'GetUserPrivacySettingRules': return $3.GetUserPrivacySettingRulesRequest();
      case 'GetUserProfilePhotos': return $3.GetUserProfilePhotosRequest();
      case 'GetWallpapers': return $3.GetWallpapersRequest();
      case 'GetWebPageInstantView': return $3.GetWebPageInstantViewRequest();
      case 'GetWebPagePreview': return $3.GetWebPagePreviewRequest();
      case 'ImportContacts': return $3.ImportContactsRequest();
      case 'JoinChat': return $3.JoinChatRequest();
      case 'JoinChatByInviteLink': return $3.JoinChatByInviteLinkRequest();
      case 'LeaveChat': return $3.LeaveChatRequest();
      case 'LogOut': return $3.LogOutRequest();
      case 'OpenChat': return $3.OpenChatRequest();
      case 'OpenMessageContent': return $3.OpenMessageContentRequest();
      case 'OptimizeStorage': return $3.OptimizeStorageRequest();
      case 'ParseTextEntities': return $3.ParseTextEntitiesRequest();
      case 'PinSupergroupMessage': return $3.PinSupergroupMessageRequest();
      case 'PingProxy': return $3.PingProxyRequest();
      case 'ProcessDcUpdate': return $3.ProcessDcUpdateRequest();
      case 'ReadAllChatMentions': return $3.ReadAllChatMentionsRequest();
      case 'RecoverAuthenticationPassword': return $3.RecoverAuthenticationPasswordRequest();
      case 'RecoverPassword': return $3.RecoverPasswordRequest();
      case 'RegisterDevice': return $3.RegisterDeviceRequest();
      case 'RemoveContacts': return $3.RemoveContactsRequest();
      case 'RemoveFavoriteSticker': return $3.RemoveFavoriteStickerRequest();
      case 'RemoveProxy': return $3.RemoveProxyRequest();
      case 'RemoveRecentHashtag': return $3.RemoveRecentHashtagRequest();
      case 'RemoveRecentSticker': return $3.RemoveRecentStickerRequest();
      case 'RemoveRecentlyFoundChat': return $3.RemoveRecentlyFoundChatRequest();
      case 'RemoveSavedAnimation': return $3.RemoveSavedAnimationRequest();
      case 'RemoveStickerFromSet': return $3.RemoveStickerFromSetRequest();
      case 'RemoveTopChat': return $3.RemoveTopChatRequest();
      case 'ReorderInstalledStickerSets': return $3.ReorderInstalledStickerSetsRequest();
      case 'ReportChat': return $3.ReportChatRequest();
      case 'ReportSupergroupSpam': return $3.ReportSupergroupSpamRequest();
      case 'RequestAuthenticationPasswordRecovery': return $3.RequestAuthenticationPasswordRecoveryRequest();
      case 'RequestPasswordRecovery': return $3.RequestPasswordRecoveryRequest();
      case 'ResendAuthenticationCode': return $3.ResendAuthenticationCodeRequest();
      case 'ResendChangePhoneNumberCode': return $3.ResendChangePhoneNumberCodeRequest();
      case 'ResendEmailAddressVerificationCode': return $3.ResendEmailAddressVerificationCodeRequest();
      case 'ResendPhoneNumberConfirmationCode': return $3.ResendPhoneNumberConfirmationCodeRequest();
      case 'ResendPhoneNumberVerificationCode': return $3.ResendPhoneNumberVerificationCodeRequest();
      case 'ResetAllNotificationSettings': return $3.ResetAllNotificationSettingsRequest();
      case 'ResetNetworkStatistics': return $3.ResetNetworkStatisticsRequest();
      case 'SearchCallMessages': return $3.SearchCallMessagesRequest();
      case 'SearchChatMembers': return $3.SearchChatMembersRequest();
      case 'SearchChatMessages': return $3.SearchChatMessagesRequest();
      case 'SearchChatRecentLocationMessages': return $3.SearchChatRecentLocationMessagesRequest();
      case 'SearchChats': return $3.SearchChatsRequest();
      case 'SearchChatsOnServer': return $3.SearchChatsOnServerRequest();
      case 'SearchContacts': return $3.SearchContactsRequest();
      case 'SearchHashtags': return $3.SearchHashtagsRequest();
      case 'SearchInstalledStickerSets': return $3.SearchInstalledStickerSetsRequest();
      case 'SearchMessages': return $3.SearchMessagesRequest();
      case 'SearchPublicChat': return $3.SearchPublicChatRequest();
      case 'SearchPublicChats': return $3.SearchPublicChatsRequest();
      case 'SearchSecretMessages': return $3.SearchSecretMessagesRequest();
      case 'SearchStickerSet': return $3.SearchStickerSetRequest();
      case 'SearchStickerSets': return $3.SearchStickerSetsRequest();
      case 'SearchStickers': return $3.SearchStickersRequest();
      case 'SendBotStartMessage': return $3.SendBotStartMessageRequest();
      case 'SendCallDebugInformation': return $3.SendCallDebugInformationRequest();
      case 'SendCallRating': return $3.SendCallRatingRequest();
      case 'SendChatAction': return $3.SendChatActionRequest();
      case 'SendChatScreenshotTakenNotification': return $3.SendChatScreenshotTakenNotificationRequest();
      case 'SendChatSetTTLMessage': return $3.SendChatSetTTLMessageRequest();
      case 'SendCustomRequest': return $3.SendCustomRequestRequest();
      case 'SendEmailAddressVerificationCode': return $3.SendEmailAddressVerificationCodeRequest();
      case 'SendInlineQueryResultMessage': return $3.SendInlineQueryResultMessageRequest();
      case 'SendMessage': return $3.SendMessageRequest();
      case 'SendMessageAlbum': return $3.SendMessageAlbumRequest();
      case 'SendPassportAuthorizationForm': return $3.SendPassportAuthorizationFormRequest();
      case 'SendPaymentForm': return $3.SendPaymentFormRequest();
      case 'SendPhoneNumberConfirmationCode': return $3.SendPhoneNumberConfirmationCodeRequest();
      case 'SendPhoneNumberVerificationCode': return $3.SendPhoneNumberVerificationCodeRequest();
      case 'SetAccountTTL': return $3.SetAccountTTLRequest();
      case 'SetAlarm': return $3.SetAlarmRequest();
      case 'SetAuthenticationPhoneNumber': return $3.SetAuthenticationPhoneNumberRequest();
      case 'SetBio': return $3.SetBioRequest();
      case 'SetBotUpdatesStatus': return $3.SetBotUpdatesStatusRequest();
      case 'SetChatClientData': return $3.SetChatClientDataRequest();
      case 'SetChatDraftMessage': return $3.SetChatDraftMessageRequest();
      case 'SetChatMemberStatus': return $3.SetChatMemberStatusRequest();
      case 'SetChatNotificationSettings': return $3.SetChatNotificationSettingsRequest();
      case 'SetChatPhoto': return $3.SetChatPhotoRequest();
      case 'SetChatTitle': return $3.SetChatTitleRequest();
      case 'SetCustomLanguagePack': return $3.SetCustomLanguagePackRequest();
      case 'SetCustomLanguagePackString': return $3.SetCustomLanguagePackStringRequest();
      case 'SetDatabaseEncryptionKey': return $3.SetDatabaseEncryptionKeyRequest();
      case 'SetFileGenerationProgress': return $3.SetFileGenerationProgressRequest();
      case 'SetGameScore': return $3.SetGameScoreRequest();
      case 'SetInlineGameScore': return $3.SetInlineGameScoreRequest();
      case 'SetName': return $3.SetNameRequest();
      case 'SetNetworkType': return $3.SetNetworkTypeRequest();
      case 'SetOption': return $3.SetOptionRequest();
      case 'SetPassportElement': return $3.SetPassportElementRequest();
      case 'SetPassportElementErrors': return $3.SetPassportElementErrorsRequest();
      case 'SetPassword': return $3.SetPasswordRequest();
      case 'SetPinnedChats': return $3.SetPinnedChatsRequest();
      case 'SetProfilePhoto': return $3.SetProfilePhotoRequest();
      case 'SetRecoveryEmailAddress': return $3.SetRecoveryEmailAddressRequest();
      case 'SetScopeNotificationSettings': return $3.SetScopeNotificationSettingsRequest();
      case 'SetStickerPositionInSet': return $3.SetStickerPositionInSetRequest();
      case 'SetSupergroupDescription': return $3.SetSupergroupDescriptionRequest();
      case 'SetSupergroupStickerSet': return $3.SetSupergroupStickerSetRequest();
      case 'SetSupergroupUsername': return $3.SetSupergroupUsernameRequest();
      case 'SetTdlibParameters': return $3.SetTdlibParametersRequest();
      case 'SetUserPrivacySettingRules': return $3.SetUserPrivacySettingRulesRequest();
      case 'SetUsername': return $3.SetUsernameRequest();
      case 'TerminateAllOtherSessions': return $3.TerminateAllOtherSessionsRequest();
      case 'TerminateSession': return $3.TerminateSessionRequest();
      case 'TestCallBytes': return $3.TestCallBytesRequest();
      case 'TestCallEmpty': return $3.TestCallEmptyRequest();
      case 'TestCallString': return $3.TestCallStringRequest();
      case 'TestCallVectorInt': return $3.TestCallVectorIntRequest();
      case 'TestCallVectorIntObject': return $3.TestCallVectorIntObjectRequest();
      case 'TestCallVectorString': return $3.TestCallVectorStringRequest();
      case 'TestCallVectorStringObject': return $3.TestCallVectorStringObjectRequest();
      case 'TestGetDifference': return $3.TestGetDifferenceRequest();
      case 'TestNetwork': return $3.TestNetworkRequest();
      case 'TestSquareInt': return $3.TestSquareIntRequest();
      case 'TestUseError': return $3.TestUseErrorRequest();
      case 'TestUseUpdate': return $3.TestUseUpdateRequest();
      case 'ToggleBasicGroupAdministrators': return $3.ToggleBasicGroupAdministratorsRequest();
      case 'ToggleChatDefaultDisableNotification': return $3.ToggleChatDefaultDisableNotificationRequest();
      case 'ToggleChatIsMarkedAsUnread': return $3.ToggleChatIsMarkedAsUnreadRequest();
      case 'ToggleChatIsPinned': return $3.ToggleChatIsPinnedRequest();
      case 'ToggleSupergroupInvites': return $3.ToggleSupergroupInvitesRequest();
      case 'ToggleSupergroupIsAllHistoryAvailable': return $3.ToggleSupergroupIsAllHistoryAvailableRequest();
      case 'ToggleSupergroupSignMessages': return $3.ToggleSupergroupSignMessagesRequest();
      case 'UnblockUser': return $3.UnblockUserRequest();
      case 'UnpinSupergroupMessage': return $3.UnpinSupergroupMessageRequest();
      case 'UpgradeBasicGroupChatToSupergroupChat': return $3.UpgradeBasicGroupChatToSupergroupChatRequest();
      case 'UploadFile': return $3.UploadFileRequest();
      case 'UploadStickerFile': return $3.UploadStickerFileRequest();
      case 'ValidateOrderInfo': return $3.ValidateOrderInfoRequest();
      case 'ViewMessages': return $3.ViewMessagesRequest();
      case 'ViewTrendingStickerSets': return $3.ViewTrendingStickerSetsRequest();
      default: throw $core.ArgumentError('Unknown method: $method');
    }
  }

  $async.Future<$pb.GeneratedMessage> handleCall($pb.ServerContext ctx, $core.String method, $pb.GeneratedMessage request) {
    switch (method) {
      case 'AcceptCall': return this.acceptCall(ctx, request);
      case 'AcceptTermsOfService': return this.acceptTermsOfService(ctx, request);
      case 'AddChatMember': return this.addChatMember(ctx, request);
      case 'AddChatMembers': return this.addChatMembers(ctx, request);
      case 'AddFavoriteSticker': return this.addFavoriteSticker(ctx, request);
      case 'AddLocalMessage': return this.addLocalMessage(ctx, request);
      case 'AddNetworkStatistics': return this.addNetworkStatistics(ctx, request);
      case 'AddProxy': return this.addProxy(ctx, request);
      case 'AddRecentSticker': return this.addRecentSticker(ctx, request);
      case 'AddRecentlyFoundChat': return this.addRecentlyFoundChat(ctx, request);
      case 'AddSavedAnimation': return this.addSavedAnimation(ctx, request);
      case 'AddStickerToSet': return this.addStickerToSet(ctx, request);
      case 'AnswerCallbackQuery': return this.answerCallbackQuery(ctx, request);
      case 'AnswerCustomQuery': return this.answerCustomQuery(ctx, request);
      case 'AnswerInlineQuery': return this.answerInlineQuery(ctx, request);
      case 'AnswerPreCheckoutQuery': return this.answerPreCheckoutQuery(ctx, request);
      case 'AnswerShippingQuery': return this.answerShippingQuery(ctx, request);
      case 'BlockUser': return this.blockUser(ctx, request);
      case 'CancelDownloadFile': return this.cancelDownloadFile(ctx, request);
      case 'CancelUploadFile': return this.cancelUploadFile(ctx, request);
      case 'ChangeChatReportSpamState': return this.changeChatReportSpamState(ctx, request);
      case 'ChangeImportedContacts': return this.changeImportedContacts(ctx, request);
      case 'ChangePhoneNumber': return this.changePhoneNumber(ctx, request);
      case 'ChangeStickerSet': return this.changeStickerSet(ctx, request);
      case 'CheckAuthenticationBotToken': return this.checkAuthenticationBotToken(ctx, request);
      case 'CheckAuthenticationCode': return this.checkAuthenticationCode(ctx, request);
      case 'CheckAuthenticationPassword': return this.checkAuthenticationPassword(ctx, request);
      case 'CheckChangePhoneNumberCode': return this.checkChangePhoneNumberCode(ctx, request);
      case 'CheckChatInviteLink': return this.checkChatInviteLink(ctx, request);
      case 'CheckChatUsername': return this.checkChatUsername(ctx, request);
      case 'CheckDatabaseEncryptionKey': return this.checkDatabaseEncryptionKey(ctx, request);
      case 'CheckEmailAddressVerificationCode': return this.checkEmailAddressVerificationCode(ctx, request);
      case 'CheckPhoneNumberConfirmationCode': return this.checkPhoneNumberConfirmationCode(ctx, request);
      case 'CheckPhoneNumberVerificationCode': return this.checkPhoneNumberVerificationCode(ctx, request);
      case 'CleanFileName': return this.cleanFileName(ctx, request);
      case 'ClearAllDraftMessages': return this.clearAllDraftMessages(ctx, request);
      case 'ClearImportedContacts': return this.clearImportedContacts(ctx, request);
      case 'ClearRecentStickers': return this.clearRecentStickers(ctx, request);
      case 'ClearRecentlyFoundChats': return this.clearRecentlyFoundChats(ctx, request);
      case 'Close': return this.close(ctx, request);
      case 'CloseChat': return this.closeChat(ctx, request);
      case 'CloseSecretChat': return this.closeSecretChat(ctx, request);
      case 'CreateBasicGroupChat': return this.createBasicGroupChat(ctx, request);
      case 'CreateCall': return this.createCall(ctx, request);
      case 'CreateNewBasicGroupChat': return this.createNewBasicGroupChat(ctx, request);
      case 'CreateNewSecretChat': return this.createNewSecretChat(ctx, request);
      case 'CreateNewStickerSet': return this.createNewStickerSet(ctx, request);
      case 'CreateNewSupergroupChat': return this.createNewSupergroupChat(ctx, request);
      case 'CreatePrivateChat': return this.createPrivateChat(ctx, request);
      case 'CreateSecretChat': return this.createSecretChat(ctx, request);
      case 'CreateSupergroupChat': return this.createSupergroupChat(ctx, request);
      case 'CreateTemporaryPassword': return this.createTemporaryPassword(ctx, request);
      case 'DeleteAccount': return this.deleteAccount(ctx, request);
      case 'DeleteChatHistory': return this.deleteChatHistory(ctx, request);
      case 'DeleteChatMessagesFromUser': return this.deleteChatMessagesFromUser(ctx, request);
      case 'DeleteChatReplyMarkup': return this.deleteChatReplyMarkup(ctx, request);
      case 'DeleteFile': return this.deleteFile(ctx, request);
      case 'DeleteLanguagePack': return this.deleteLanguagePack(ctx, request);
      case 'DeleteMessages': return this.deleteMessages(ctx, request);
      case 'DeletePassportElement': return this.deletePassportElement(ctx, request);
      case 'DeleteProfilePhoto': return this.deleteProfilePhoto(ctx, request);
      case 'DeleteSavedCredentials': return this.deleteSavedCredentials(ctx, request);
      case 'DeleteSavedOrderInfo': return this.deleteSavedOrderInfo(ctx, request);
      case 'DeleteSupergroup': return this.deleteSupergroup(ctx, request);
      case 'Destroy': return this.destroy(ctx, request);
      case 'DisableProxy': return this.disableProxy(ctx, request);
      case 'DiscardCall': return this.discardCall(ctx, request);
      case 'DisconnectAllWebsites': return this.disconnectAllWebsites(ctx, request);
      case 'DisconnectWebsite': return this.disconnectWebsite(ctx, request);
      case 'DownloadFile': return this.downloadFile(ctx, request);
      case 'EditCustomLanguagePackInfo': return this.editCustomLanguagePackInfo(ctx, request);
      case 'EditInlineMessageCaption': return this.editInlineMessageCaption(ctx, request);
      case 'EditInlineMessageLiveLocation': return this.editInlineMessageLiveLocation(ctx, request);
      case 'EditInlineMessageMedia': return this.editInlineMessageMedia(ctx, request);
      case 'EditInlineMessageReplyMarkup': return this.editInlineMessageReplyMarkup(ctx, request);
      case 'EditInlineMessageText': return this.editInlineMessageText(ctx, request);
      case 'EditMessageCaption': return this.editMessageCaption(ctx, request);
      case 'EditMessageLiveLocation': return this.editMessageLiveLocation(ctx, request);
      case 'EditMessageMedia': return this.editMessageMedia(ctx, request);
      case 'EditMessageReplyMarkup': return this.editMessageReplyMarkup(ctx, request);
      case 'EditMessageText': return this.editMessageText(ctx, request);
      case 'EditProxy': return this.editProxy(ctx, request);
      case 'EnableProxy': return this.enableProxy(ctx, request);
      case 'FinishFileGeneration': return this.finishFileGeneration(ctx, request);
      case 'ForwardMessages': return this.forwardMessages(ctx, request);
      case 'GenerateChatInviteLink': return this.generateChatInviteLink(ctx, request);
      case 'GetAccountTTL': return this.getAccountTTL(ctx, request);
      case 'GetActiveLiveLocationMessages': return this.getActiveLiveLocationMessages(ctx, request);
      case 'GetActiveSessions': return this.getActiveSessions(ctx, request);
      case 'GetAllPassportElements': return this.getAllPassportElements(ctx, request);
      case 'GetArchivedStickerSets': return this.getArchivedStickerSets(ctx, request);
      case 'GetAttachedStickerSets': return this.getAttachedStickerSets(ctx, request);
      case 'GetAuthorizationState': return this.getAuthorizationState(ctx, request);
      case 'GetBasicGroup': return this.getBasicGroup(ctx, request);
      case 'GetBasicGroupFullInfo': return this.getBasicGroupFullInfo(ctx, request);
      case 'GetBlockedUsers': return this.getBlockedUsers(ctx, request);
      case 'GetCallbackQueryAnswer': return this.getCallbackQueryAnswer(ctx, request);
      case 'GetChat': return this.getChat(ctx, request);
      case 'GetChatAdministrators': return this.getChatAdministrators(ctx, request);
      case 'GetChatEventLog': return this.getChatEventLog(ctx, request);
      case 'GetChatHistory': return this.getChatHistory(ctx, request);
      case 'GetChatMember': return this.getChatMember(ctx, request);
      case 'GetChatMessageByDate': return this.getChatMessageByDate(ctx, request);
      case 'GetChatMessageCount': return this.getChatMessageCount(ctx, request);
      case 'GetChatPinnedMessage': return this.getChatPinnedMessage(ctx, request);
      case 'GetChatReportSpamState': return this.getChatReportSpamState(ctx, request);
      case 'GetChats': return this.getChats(ctx, request);
      case 'GetConnectedWebsites': return this.getConnectedWebsites(ctx, request);
      case 'GetContacts': return this.getContacts(ctx, request);
      case 'GetCountryCode': return this.getCountryCode(ctx, request);
      case 'GetCreatedPublicChats': return this.getCreatedPublicChats(ctx, request);
      case 'GetDeepLinkInfo': return this.getDeepLinkInfo(ctx, request);
      case 'GetFavoriteStickers': return this.getFavoriteStickers(ctx, request);
      case 'GetFile': return this.getFile(ctx, request);
      case 'GetFileExtension': return this.getFileExtension(ctx, request);
      case 'GetFileMimeType': return this.getFileMimeType(ctx, request);
      case 'GetGameHighScores': return this.getGameHighScores(ctx, request);
      case 'GetGroupsInCommon': return this.getGroupsInCommon(ctx, request);
      case 'GetImportedContactCount': return this.getImportedContactCount(ctx, request);
      case 'GetInlineGameHighScores': return this.getInlineGameHighScores(ctx, request);
      case 'GetInlineQueryResults': return this.getInlineQueryResults(ctx, request);
      case 'GetInstalledStickerSets': return this.getInstalledStickerSets(ctx, request);
      case 'GetInviteText': return this.getInviteText(ctx, request);
      case 'GetLanguagePackString': return this.getLanguagePackString(ctx, request);
      case 'GetLanguagePackStrings': return this.getLanguagePackStrings(ctx, request);
      case 'GetLocalizationTargetInfo': return this.getLocalizationTargetInfo(ctx, request);
      case 'GetMapThumbnailFile': return this.getMapThumbnailFile(ctx, request);
      case 'GetMe': return this.getMe(ctx, request);
      case 'GetMessage': return this.getMessage(ctx, request);
      case 'GetMessages': return this.getMessages(ctx, request);
      case 'GetNetworkStatistics': return this.getNetworkStatistics(ctx, request);
      case 'GetOption': return this.getOption(ctx, request);
      case 'GetPassportAuthorizationForm': return this.getPassportAuthorizationForm(ctx, request);
      case 'GetPassportElement': return this.getPassportElement(ctx, request);
      case 'GetPasswordState': return this.getPasswordState(ctx, request);
      case 'GetPaymentForm': return this.getPaymentForm(ctx, request);
      case 'GetPaymentReceipt': return this.getPaymentReceipt(ctx, request);
      case 'GetPreferredCountryLanguage': return this.getPreferredCountryLanguage(ctx, request);
      case 'GetProxies': return this.getProxies(ctx, request);
      case 'GetProxyLink': return this.getProxyLink(ctx, request);
      case 'GetPublicMessageLink': return this.getPublicMessageLink(ctx, request);
      case 'GetRecentInlineBots': return this.getRecentInlineBots(ctx, request);
      case 'GetRecentStickers': return this.getRecentStickers(ctx, request);
      case 'GetRecentlyVisitedTMeUrls': return this.getRecentlyVisitedTMeUrls(ctx, request);
      case 'GetRecoveryEmailAddress': return this.getRecoveryEmailAddress(ctx, request);
      case 'GetRemoteFile': return this.getRemoteFile(ctx, request);
      case 'GetRepliedMessage': return this.getRepliedMessage(ctx, request);
      case 'GetSavedAnimations': return this.getSavedAnimations(ctx, request);
      case 'GetSavedOrderInfo': return this.getSavedOrderInfo(ctx, request);
      case 'GetScopeNotificationSettings': return this.getScopeNotificationSettings(ctx, request);
      case 'GetSecretChat': return this.getSecretChat(ctx, request);
      case 'GetStickerEmojis': return this.getStickerEmojis(ctx, request);
      case 'GetStickerSet': return this.getStickerSet(ctx, request);
      case 'GetStickers': return this.getStickers(ctx, request);
      case 'GetStorageStatistics': return this.getStorageStatistics(ctx, request);
      case 'GetStorageStatisticsFast': return this.getStorageStatisticsFast(ctx, request);
      case 'GetSupergroup': return this.getSupergroup(ctx, request);
      case 'GetSupergroupFullInfo': return this.getSupergroupFullInfo(ctx, request);
      case 'GetSupergroupMembers': return this.getSupergroupMembers(ctx, request);
      case 'GetSupportUser': return this.getSupportUser(ctx, request);
      case 'GetTemporaryPasswordState': return this.getTemporaryPasswordState(ctx, request);
      case 'GetTextEntities': return this.getTextEntities(ctx, request);
      case 'GetTopChats': return this.getTopChats(ctx, request);
      case 'GetTrendingStickerSets': return this.getTrendingStickerSets(ctx, request);
      case 'GetUser': return this.getUser(ctx, request);
      case 'GetUserFullInfo': return this.getUserFullInfo(ctx, request);
      case 'GetUserPrivacySettingRules': return this.getUserPrivacySettingRules(ctx, request);
      case 'GetUserProfilePhotos': return this.getUserProfilePhotos(ctx, request);
      case 'GetWallpapers': return this.getWallpapers(ctx, request);
      case 'GetWebPageInstantView': return this.getWebPageInstantView(ctx, request);
      case 'GetWebPagePreview': return this.getWebPagePreview(ctx, request);
      case 'ImportContacts': return this.importContacts(ctx, request);
      case 'JoinChat': return this.joinChat(ctx, request);
      case 'JoinChatByInviteLink': return this.joinChatByInviteLink(ctx, request);
      case 'LeaveChat': return this.leaveChat(ctx, request);
      case 'LogOut': return this.logOut(ctx, request);
      case 'OpenChat': return this.openChat(ctx, request);
      case 'OpenMessageContent': return this.openMessageContent(ctx, request);
      case 'OptimizeStorage': return this.optimizeStorage(ctx, request);
      case 'ParseTextEntities': return this.parseTextEntities(ctx, request);
      case 'PinSupergroupMessage': return this.pinSupergroupMessage(ctx, request);
      case 'PingProxy': return this.pingProxy(ctx, request);
      case 'ProcessDcUpdate': return this.processDcUpdate(ctx, request);
      case 'ReadAllChatMentions': return this.readAllChatMentions(ctx, request);
      case 'RecoverAuthenticationPassword': return this.recoverAuthenticationPassword(ctx, request);
      case 'RecoverPassword': return this.recoverPassword(ctx, request);
      case 'RegisterDevice': return this.registerDevice(ctx, request);
      case 'RemoveContacts': return this.removeContacts(ctx, request);
      case 'RemoveFavoriteSticker': return this.removeFavoriteSticker(ctx, request);
      case 'RemoveProxy': return this.removeProxy(ctx, request);
      case 'RemoveRecentHashtag': return this.removeRecentHashtag(ctx, request);
      case 'RemoveRecentSticker': return this.removeRecentSticker(ctx, request);
      case 'RemoveRecentlyFoundChat': return this.removeRecentlyFoundChat(ctx, request);
      case 'RemoveSavedAnimation': return this.removeSavedAnimation(ctx, request);
      case 'RemoveStickerFromSet': return this.removeStickerFromSet(ctx, request);
      case 'RemoveTopChat': return this.removeTopChat(ctx, request);
      case 'ReorderInstalledStickerSets': return this.reorderInstalledStickerSets(ctx, request);
      case 'ReportChat': return this.reportChat(ctx, request);
      case 'ReportSupergroupSpam': return this.reportSupergroupSpam(ctx, request);
      case 'RequestAuthenticationPasswordRecovery': return this.requestAuthenticationPasswordRecovery(ctx, request);
      case 'RequestPasswordRecovery': return this.requestPasswordRecovery(ctx, request);
      case 'ResendAuthenticationCode': return this.resendAuthenticationCode(ctx, request);
      case 'ResendChangePhoneNumberCode': return this.resendChangePhoneNumberCode(ctx, request);
      case 'ResendEmailAddressVerificationCode': return this.resendEmailAddressVerificationCode(ctx, request);
      case 'ResendPhoneNumberConfirmationCode': return this.resendPhoneNumberConfirmationCode(ctx, request);
      case 'ResendPhoneNumberVerificationCode': return this.resendPhoneNumberVerificationCode(ctx, request);
      case 'ResetAllNotificationSettings': return this.resetAllNotificationSettings(ctx, request);
      case 'ResetNetworkStatistics': return this.resetNetworkStatistics(ctx, request);
      case 'SearchCallMessages': return this.searchCallMessages(ctx, request);
      case 'SearchChatMembers': return this.searchChatMembers(ctx, request);
      case 'SearchChatMessages': return this.searchChatMessages(ctx, request);
      case 'SearchChatRecentLocationMessages': return this.searchChatRecentLocationMessages(ctx, request);
      case 'SearchChats': return this.searchChats(ctx, request);
      case 'SearchChatsOnServer': return this.searchChatsOnServer(ctx, request);
      case 'SearchContacts': return this.searchContacts(ctx, request);
      case 'SearchHashtags': return this.searchHashtags(ctx, request);
      case 'SearchInstalledStickerSets': return this.searchInstalledStickerSets(ctx, request);
      case 'SearchMessages': return this.searchMessages(ctx, request);
      case 'SearchPublicChat': return this.searchPublicChat(ctx, request);
      case 'SearchPublicChats': return this.searchPublicChats(ctx, request);
      case 'SearchSecretMessages': return this.searchSecretMessages(ctx, request);
      case 'SearchStickerSet': return this.searchStickerSet(ctx, request);
      case 'SearchStickerSets': return this.searchStickerSets(ctx, request);
      case 'SearchStickers': return this.searchStickers(ctx, request);
      case 'SendBotStartMessage': return this.sendBotStartMessage(ctx, request);
      case 'SendCallDebugInformation': return this.sendCallDebugInformation(ctx, request);
      case 'SendCallRating': return this.sendCallRating(ctx, request);
      case 'SendChatAction': return this.sendChatAction(ctx, request);
      case 'SendChatScreenshotTakenNotification': return this.sendChatScreenshotTakenNotification(ctx, request);
      case 'SendChatSetTTLMessage': return this.sendChatSetTTLMessage(ctx, request);
      case 'SendCustomRequest': return this.sendCustomRequest(ctx, request);
      case 'SendEmailAddressVerificationCode': return this.sendEmailAddressVerificationCode(ctx, request);
      case 'SendInlineQueryResultMessage': return this.sendInlineQueryResultMessage(ctx, request);
      case 'SendMessage': return this.sendMessage(ctx, request);
      case 'SendMessageAlbum': return this.sendMessageAlbum(ctx, request);
      case 'SendPassportAuthorizationForm': return this.sendPassportAuthorizationForm(ctx, request);
      case 'SendPaymentForm': return this.sendPaymentForm(ctx, request);
      case 'SendPhoneNumberConfirmationCode': return this.sendPhoneNumberConfirmationCode(ctx, request);
      case 'SendPhoneNumberVerificationCode': return this.sendPhoneNumberVerificationCode(ctx, request);
      case 'SetAccountTTL': return this.setAccountTTL(ctx, request);
      case 'SetAlarm': return this.setAlarm(ctx, request);
      case 'SetAuthenticationPhoneNumber': return this.setAuthenticationPhoneNumber(ctx, request);
      case 'SetBio': return this.setBio(ctx, request);
      case 'SetBotUpdatesStatus': return this.setBotUpdatesStatus(ctx, request);
      case 'SetChatClientData': return this.setChatClientData(ctx, request);
      case 'SetChatDraftMessage': return this.setChatDraftMessage(ctx, request);
      case 'SetChatMemberStatus': return this.setChatMemberStatus(ctx, request);
      case 'SetChatNotificationSettings': return this.setChatNotificationSettings(ctx, request);
      case 'SetChatPhoto': return this.setChatPhoto(ctx, request);
      case 'SetChatTitle': return this.setChatTitle(ctx, request);
      case 'SetCustomLanguagePack': return this.setCustomLanguagePack(ctx, request);
      case 'SetCustomLanguagePackString': return this.setCustomLanguagePackString(ctx, request);
      case 'SetDatabaseEncryptionKey': return this.setDatabaseEncryptionKey(ctx, request);
      case 'SetFileGenerationProgress': return this.setFileGenerationProgress(ctx, request);
      case 'SetGameScore': return this.setGameScore(ctx, request);
      case 'SetInlineGameScore': return this.setInlineGameScore(ctx, request);
      case 'SetName': return this.setName(ctx, request);
      case 'SetNetworkType': return this.setNetworkType(ctx, request);
      case 'SetOption': return this.setOption(ctx, request);
      case 'SetPassportElement': return this.setPassportElement(ctx, request);
      case 'SetPassportElementErrors': return this.setPassportElementErrors(ctx, request);
      case 'SetPassword': return this.setPassword(ctx, request);
      case 'SetPinnedChats': return this.setPinnedChats(ctx, request);
      case 'SetProfilePhoto': return this.setProfilePhoto(ctx, request);
      case 'SetRecoveryEmailAddress': return this.setRecoveryEmailAddress(ctx, request);
      case 'SetScopeNotificationSettings': return this.setScopeNotificationSettings(ctx, request);
      case 'SetStickerPositionInSet': return this.setStickerPositionInSet(ctx, request);
      case 'SetSupergroupDescription': return this.setSupergroupDescription(ctx, request);
      case 'SetSupergroupStickerSet': return this.setSupergroupStickerSet(ctx, request);
      case 'SetSupergroupUsername': return this.setSupergroupUsername(ctx, request);
      case 'SetTdlibParameters': return this.setTdlibParameters(ctx, request);
      case 'SetUserPrivacySettingRules': return this.setUserPrivacySettingRules(ctx, request);
      case 'SetUsername': return this.setUsername(ctx, request);
      case 'TerminateAllOtherSessions': return this.terminateAllOtherSessions(ctx, request);
      case 'TerminateSession': return this.terminateSession(ctx, request);
      case 'TestCallBytes': return this.testCallBytes(ctx, request);
      case 'TestCallEmpty': return this.testCallEmpty(ctx, request);
      case 'TestCallString': return this.testCallString(ctx, request);
      case 'TestCallVectorInt': return this.testCallVectorInt(ctx, request);
      case 'TestCallVectorIntObject': return this.testCallVectorIntObject(ctx, request);
      case 'TestCallVectorString': return this.testCallVectorString(ctx, request);
      case 'TestCallVectorStringObject': return this.testCallVectorStringObject(ctx, request);
      case 'TestGetDifference': return this.testGetDifference(ctx, request);
      case 'TestNetwork': return this.testNetwork(ctx, request);
      case 'TestSquareInt': return this.testSquareInt(ctx, request);
      case 'TestUseError': return this.testUseError(ctx, request);
      case 'TestUseUpdate': return this.testUseUpdate(ctx, request);
      case 'ToggleBasicGroupAdministrators': return this.toggleBasicGroupAdministrators(ctx, request);
      case 'ToggleChatDefaultDisableNotification': return this.toggleChatDefaultDisableNotification(ctx, request);
      case 'ToggleChatIsMarkedAsUnread': return this.toggleChatIsMarkedAsUnread(ctx, request);
      case 'ToggleChatIsPinned': return this.toggleChatIsPinned(ctx, request);
      case 'ToggleSupergroupInvites': return this.toggleSupergroupInvites(ctx, request);
      case 'ToggleSupergroupIsAllHistoryAvailable': return this.toggleSupergroupIsAllHistoryAvailable(ctx, request);
      case 'ToggleSupergroupSignMessages': return this.toggleSupergroupSignMessages(ctx, request);
      case 'UnblockUser': return this.unblockUser(ctx, request);
      case 'UnpinSupergroupMessage': return this.unpinSupergroupMessage(ctx, request);
      case 'UpgradeBasicGroupChatToSupergroupChat': return this.upgradeBasicGroupChatToSupergroupChat(ctx, request);
      case 'UploadFile': return this.uploadFile(ctx, request);
      case 'UploadStickerFile': return this.uploadStickerFile(ctx, request);
      case 'ValidateOrderInfo': return this.validateOrderInfo(ctx, request);
      case 'ViewMessages': return this.viewMessages(ctx, request);
      case 'ViewTrendingStickerSets': return this.viewTrendingStickerSets(ctx, request);
      default: throw $core.ArgumentError('Unknown method: $method');
    }
  }

  $core.Map<$core.String, $core.dynamic> get $json => tdServerServiceBase$json;
  $core.Map<$core.String, $core.Map<$core.String, $core.dynamic>> get $messageJson => tdServerServiceBase$messageJson;
}

