name: client_core
version: 1.0.0
author: dongfeng

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  # base deps
  flutter:
    sdk: flutter

  # third-party deps

  asn1lib: ^0.5.0
  convert: ^2.1.1
  crypto: ^2.1.3
  date_format: ^1.0.8
  event_bus: ^1.1.0
  fixnum: ^0.10.11
  hex: ^0.1.2
  # jaguar_query_sqflite: ^2.2.11
  jaguar_query_sqflite:
    path: ../jaguar_query_sqflite-2.2.11-mod
  jaguar_orm: ^2.2.7
  json_annotation: ^3.0.1
  logger: ^0.7.0+2
  path: ^1.6.4
  path_provider: ^1.5.1
  path_provider_macos: ^0.0.1
  pointycastle: ^1.0.1
  protobuf: ^1.0.0
  steel_crypt: ^1.5.3
  sqflite: ^1.1.7

  anymmkv:
    path: ../anymmkv


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  jaguar_orm_gen: 
    path: ../jaguar_orm_gen-2.2.29-mod
  json_serializable: ^3.1.0
  protoc_plugin: ^19.0.0
